export const styles = {
  page: { fontFamily: "'Source Sans Pro','Segoe UI',sans-serif", background: "#F5F3EE", minHeight: "100vh", padding: "24px 16px 48px", color: "#1F2A24" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 12, borderBottom: "3px solid #1F2A24", paddingBottom: 16, marginBottom: 20 },
  eyebrow: { fontSize: 12, letterSpacing: 0.5, color: "#8A6D3B", marginBottom: 4 },
  titleRow: { display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap" },
  title: { fontFamily: "Georgia,'Times New Roman',serif", fontSize: 32, margin: 0, color: "#1F2A24" },
  byline: { fontSize: 12, color: "#9A9484", fontStyle: "italic" },
  version: { fontSize: 11, color: "#B7B2A3" },
  modeSwitch: { display: "flex", gap: 6 },
  modeBtn: { padding: "8px 16px", border: "1px solid #1F2A24", background: "transparent", color: "#1F2A24", borderRadius: 999, cursor: "pointer", fontSize: 14 },
  modeBtnActive: { padding: "8px 16px", border: "1px solid #1F2A24", background: "#1F2A24", color: "#F5F3EE", borderRadius: 999, cursor: "pointer", fontSize: 14 },
  errorBanner: { background: "#FBEAE8", color: "#B8443D", border: "1px solid #E7B7B1", borderRadius: 8, padding: "8px 12px", fontSize: 13, marginBottom: 16 },
  warnBanner: { background: "#FDF3E3", color: "#8A6D3B", border: "1px solid #E9D3A3", borderRadius: 8, padding: "8px 12px", fontSize: 13, marginBottom: 16 },
  loading: { fontSize: 13, color: "#6B7A5E", marginBottom: 16 },
  ongletSwitch: { display: "flex", gap: 6, marginBottom: 24, flexWrap: "wrap" },
  ongletBtn: { padding: "6px 14px", border: "1px solid #4B6455", background: "transparent", color: "#4B6455", borderRadius: 6, cursor: "pointer", fontSize: 14 },
  ongletBtnActive: { padding: "6px 14px", border: "1px solid #4B6455", background: "#4B6455", color: "#fff", borderRadius: 6, cursor: "pointer", fontSize: 14 },
  moduleBlock: { marginBottom: 28 },
  moduleTitle: { fontFamily: "Georgia,serif", fontSize: 22, borderBottom: "2px solid #1F2A24", paddingBottom: 6, marginBottom: 12 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 14 },
  card: { display: "block", background: "#fff", border: "1px solid #E3DFD3", borderRadius: 8, padding: "12px 14px" },
  cardTitre: { fontWeight: "bold", fontSize: 14.5, marginBottom: 4 },
  cardTexte: { fontSize: 13.5, lineHeight: 1.45, margin: "4px 0", color: "#3A3F35" },
  videoLink: { display: "block", fontSize: 13, color: "#8A6D3B", marginTop: 6, textDecoration: "none" },
  videoLinkSmall: { display: "block", fontSize: 12, color: "#8A6D3B", marginTop: 2, textDecoration: "none" },
  phasesList: { display: "flex", flexDirection: "column" },
  editBtn: { marginTop: 8, fontSize: 12, background: "none", border: "1px dashed #6B7A5E", borderRadius: 6, padding: "4px 8px", color: "#6B7A5E", cursor: "pointer" },
  editPanel: { marginTop: 8, padding: 8, background: "#F5F3EE", borderRadius: 6, display: "flex", flexDirection: "column", gap: 6 },
  editLabel: { fontSize: 11, color: "#6B7A5E", marginTop: 4 },
  editInput: { fontSize: 12, padding: "4px 6px", border: "1px solid #D8D3C4", borderRadius: 4 },
  phaseRow: { display: "flex", gap: 4 },
  removeBtn: { border: "none", background: "none", color: "#B8443D", cursor: "pointer" },
  addPhaseBtn: { fontSize: 11, alignSelf: "flex-start", background: "none", border: "none", color: "#8A6D3B", cursor: "pointer", padding: 0 },
  doneBtn: { marginTop: 4, fontSize: 12, background: "#1F2A24", color: "#fff", border: "none", borderRadius: 6, padding: "6px 10px", cursor: "pointer" },
  evalRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, padding: "8px 10px", background: "#fff", border: "1px solid #E3DFD3", borderRadius: 8, marginBottom: 8 },
  evalLabel: { fontSize: 13.5, flex: 1 },
  evalChoices: { display: "flex", gap: 4 },
  evalChoiceBtn: { fontSize: 12, padding: "4px 10px", border: "1px solid #C8C2B2", borderRadius: 999, background: "#fff", cursor: "pointer", color: "#6B6455" },
  evalChoiceBtnActive: { fontSize: 12, padding: "4px 10px", border: "1px solid #4B6455", borderRadius: 999, background: "#4B6455", cursor: "pointer", color: "#fff" },
  evalCheck: { width: 18, height: 18 },
  scoreBox: { background: "#fff", border: "1px solid #E3DFD3", borderRadius: 10, padding: 16, maxWidth: 420, marginTop: 20 },
  scoreTotal: { display: "flex", justifyContent: "space-between", fontWeight: "bold", fontSize: 20, color: "#8A6D3B", borderTop: "2px solid #1F2A24", marginTop: 10, paddingTop: 10 },
  saveBtn: { marginTop: 12, fontSize: 13, background: "#1F2A24", color: "#fff", border: "none", borderRadius: 6, padding: "8px 14px", cursor: "pointer" },
  nameInput: { fontSize: 14, padding: "6px 10px", border: "1px solid #D8D3C4", borderRadius: 6, marginBottom: 16, width: 220 },
  footer: { textAlign: "center", fontSize: 11, color: "#B7B2A3", marginTop: 32 },
};
